export const CONTRACT_ADDRESS = "0x618B521C3d7DAD1a2F186aD830E69ba6d5081E1E";

export const CONTRACT_ABI = [
  {
    "inputs": [{"internalType":"address","name":"_WLD","type":"address"},{"internalType":"address","name":"_H2O","type":"address"},{"internalType":"address","name":"_BTCH2O","type":"address"}],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {"inputs":[],"name":"ReentrancyGuardReentrantCall","type":"error"},
  {
    "anonymous":false,"inputs":[{"indexed":true,"name":"owner","type":"address"}],
    "name":"OwnerAdded","type":"event"
  },
  {
    "anonymous":false,"inputs":[{"indexed":true,"name":"owner","type":"address"}],
    "name":"OwnerRemoved","type":"event"
  },
  {
    "anonymous":false,"inputs":[{"indexed":true,"name":"tokenId","type":"uint256"}],
    "name":"PositionAdded","type":"event"
  },
  {
    "anonymous":false,"inputs":[{"indexed":true,"name":"tokenId","type":"uint256"}],
    "name":"PositionRemoved","type":"event"
  },
  {
    "anonymous":false,
    "inputs":[{"indexed":true,"name":"tokenId","type":"uint256"},{"indexed":false,"name":"amount0","type":"uint256"},{"indexed":false,"name":"amount1","type":"uint256"}],
    "name":"FeesCollected","type":"event"
  },
  {
    "anonymous":false,
    "inputs":[{"indexed":true,"name":"tokenIn","type":"address"},{"indexed":true,"name":"tokenOut","type":"address"},{"indexed":false,"name":"amountIn","type":"uint256"},{"indexed":false,"name":"amountOut","type":"uint256"}],
    "name":"Swapped","type":"event"
  },
  {
    "anonymous":false,
    "inputs":[{"indexed":true,"name":"tokenId","type":"uint256"},{"indexed":false,"name":"liquidity","type":"uint128"}],
    "name":"LiquidityAdded","type":"event"
  },
  {
    "anonymous":false,
    "inputs":[{"indexed":true,"name":"token","type":"address"},{"indexed":true,"name":"to","type":"address"},{"indexed":false,"name":"amount","type":"uint256"}],
    "name":"ReserveWithdrawn","type":"event"
  },
  {
    "anonymous":false,
    "inputs":[{"indexed":false,"name":"key","type":"string"},{"indexed":false,"name":"value","type":"uint256"}],
    "name":"ConfigUpdated","type":"event"
  },
  {
    "anonymous":false,"inputs":[{"indexed":false,"name":"isPaused","type":"bool"}],
    "name":"Paused","type":"event"
  },
  {
    "anonymous":false,
    "inputs":[{"indexed":false,"name":"timestamp","type":"uint256"},{"indexed":false,"name":"totalWLD","type":"uint256"}],
    "name":"ReinvestCompleted","type":"event"
  },
  {
    "inputs":[{"name":"newOwner","type":"address"}],
    "name":"addOwner","outputs":[],"stateMutability":"nonpayable","type":"function"
  },
  {
    "inputs":[{"name":"owner","type":"address"}],
    "name":"removeOwner","outputs":[],"stateMutability":"nonpayable","type":"function"
  },
  {
    "inputs":[],"name":"getOwners",
    "outputs":[{"internalType":"address[]","name":"","type":"address[]"}],
    "stateMutability":"view","type":"function"
  },
  {
    "inputs":[{"name":"bps","type":"uint256"}],
    "name":"setSlippage","outputs":[],"stateMutability":"nonpayable","type":"function"
  },
  {
    "inputs":[{"name":"secs","type":"uint256"}],
    "name":"setReinvestInterval","outputs":[],"stateMutability":"nonpayable","type":"function"
  },
  {
    "inputs":[{"name":"bps","type":"uint256"}],
    "name":"setReserveFeeBps","outputs":[],"stateMutability":"nonpayable","type":"function"
  },
  {
    "inputs":[{"name":"_h2oShareBps","type":"uint256"},{"name":"_btch2oShareBps","type":"uint256"}],
    "name":"setDistribution","outputs":[],"stateMutability":"nonpayable","type":"function"
  },
  {
    "inputs":[{"name":"_paused","type":"bool"}],
    "name":"setPaused","outputs":[],"stateMutability":"nonpayable","type":"function"
  },
  {
    "inputs":[{"name":"tokenId","type":"uint256"}],
    "name":"addPosition","outputs":[],"stateMutability":"nonpayable","type":"function"
  },
  {
    "inputs":[{"name":"tokenId","type":"uint256"}],
    "name":"removePosition","outputs":[],"stateMutability":"nonpayable","type":"function"
  },
  {
    "inputs":[],"name":"getManagedPositions",
    "outputs":[{"internalType":"uint256[]","name":"","type":"uint256[]"}],
    "stateMutability":"view","type":"function"
  },
  {
    "inputs":[{"name":"tokenIds","type":"uint256[]"}],
    "name":"updateRanges","outputs":[],"stateMutability":"nonpayable","type":"function"
  },
  {
    "inputs":[{"name":"tokenIds","type":"uint256[]"},{"name":"deadline","type":"uint256"}],
    "name":"collectFees","outputs":[],"stateMutability":"nonpayable","type":"function"
  },
  {
    "inputs":[{"name":"token","type":"address"},{"name":"amount","type":"uint256"},{"name":"to","type":"address"}],
    "name":"withdrawReserve","outputs":[],"stateMutability":"nonpayable","type":"function"
  },
  {
    "inputs":[{"name":"token","type":"address"},{"name":"to","type":"address"}],
    "name":"withdrawAll","outputs":[],"stateMutability":"nonpayable","type":"function"
  },
  {
    "inputs":[],"name":"getConfig",
    "outputs":[
      {"name":"_slippageBps","type":"uint256"},
      {"name":"_reinvestIntervalSecs","type":"uint256"},
      {"name":"_reserveFeeBps","type":"uint256"},
      {"name":"_h2oShareBps","type":"uint256"},
      {"name":"_btch2oShareBps","type":"uint256"},
      {"name":"_paused","type":"bool"},
      {"name":"_lastReinvestAt","type":"uint256"}
    ],
    "stateMutability":"view","type":"function"
  },
  {
    "inputs":[{"name":"tokenId","type":"uint256"}],"name":"getPosition",
    "outputs":[
      {"name":"token0","type":"address"},
      {"name":"token1","type":"address"},
      {"name":"fee","type":"uint24"},
      {"name":"tickLower","type":"int24"},
      {"name":"tickUpper","type":"int24"},
      {"name":"liquidity","type":"uint128"},
      {"name":"tokensOwed0","type":"uint128"},
      {"name":"tokensOwed1","type":"uint128"},
      {"name":"managed","type":"bool"},
      {"name":"isInRange","type":"bool"}
    ],
    "stateMutability":"view","type":"function"
  },
  {
    "inputs":[],"name":"getReserves",
    "outputs":[
      {"name":"wldReserve","type":"uint256"},
      {"name":"h2oReserve","type":"uint256"},
      {"name":"btch2oReserve","type":"uint256"}
    ],
    "stateMutability":"view","type":"function"
  },
  {"inputs":[],"name":"WLD","outputs":[{"type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"H2O","outputs":[{"type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"BTCH2O","outputs":[{"type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"primaryOwner","outputs":[{"type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"name":"","type":"address"}],"name":"isOwner","outputs":[{"type":"bool"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"name":"","type":"uint256"}],"name":"isManaged","outputs":[{"type":"bool"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"name":"","type":"uint256"}],"name":"inRange","outputs":[{"type":"bool"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"paused","outputs":[{"type":"bool"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"lastReinvestAt","outputs":[{"type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"slippageBps","outputs":[{"type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"reinvestIntervalSecs","outputs":[{"type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"reserveFeeBps","outputs":[{"type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"h2oShareBps","outputs":[{"type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"btch2oShareBps","outputs":[{"type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"name":"","type":"address"}],"name":"reserve","outputs":[{"type":"uint256"}],"stateMutability":"view","type":"function"},
  {
    "inputs":[{"name":"index","type":"uint256"}],"name":"managedPositions",
    "outputs":[{"type":"uint256"}],"stateMutability":"view","type":"function"
  }
];
